# website settings
website:
  title: "Bosco Bakwatanisa"                           
  description: "I am Bosco Bosco Bakwatanisa, a second year BME PhD Student.
    image: img/bosco.jpeg"
  favicon: img/IMG_6931.JPG
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/IMG_6931.JPG
    
    # your sub-pages 
    left:
      - text: Blog
        href: Blog.qmd
      - text: "Education"
        href: education/index.qmd
      - text: "Publications"
        href: Publications/index.qmd
      - text: "Photography"
        href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Study1"
        href: Study1/Study1.qmd
      - text: "Study2"
        href: Study2/Study2.qmd
      - text: "Study1Dashboard"
        href: Study1Dashboard/Study1Dashboard.qmd
      - text: "Study2Dashboard"
        href: Study2Dashboard/Study2Dashboard.qmd
     
      
    # your social media handles
    right:
      - icon: x
        href: https://x.com/bakwatanisamuto?s=11&t=G0DoPfVhmPjJTooCrau8vA
      - icon: linkedin
        href: https://www.linkedin.com/in/bakwatanisa-bosco-25b063102/
      - icon: envelope
        aria-label: email
        href: "mailto:mail.bakwabosco12@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Bosco Bakwatanisa CC BY-SA 4.0</span>
    
project:
  type: website
  output-dir: docs

  preview: 
    port: 22223
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true
  
publish:
  type: gh-pages
  branch: gh-pages
  dir: docs

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    page-layout: full
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true